import mongoose from 'mongoose';

const airbnbSchema = new mongoose.Schema({
  "listing_url": String,
  "scrape_id": Number,
  "last_scraped": String,
  "name": String,
  "summary":String,
  "description": String,
  "experiences_offered": String,
  "neighborhood_overview": String,
  "notes": Boolean,
  "transit": String,
  "access": String,
  "interaction": String,
  "house_rules": Boolean,
  "thumbnail_url": String,
  "medium_url": String,
  "picture_url":{
     "thumbnail":Boolean,
     "filename": String,
     "format": String,
     "width": Number,
     "mimetype": String,
     "etag": String,
     "id": String,
     "last_synchronized": String,
     "color_summary":[
        String,
        String,
        String
     ],
     "height":Number
  },
  "xl_picture_url": String,
  "host_id": Number,
  "host_url": String,
  "host_name": String,
  "host_since": String,
  "host_location": String,
  "host_about": String,
  "host_response_time":String,
  "host_response_rate":Number,
  "host_acceptance_rate":Boolean,
  "host_thumbnail_url":String,
  "host_picture_url":String,
  "host_neighbourhood": String,
  "host_listings_count": Number,
  "host_total_listings_count": Number,
  "host_verifications":[
     String,
     String,
     String,
     String,
     String
  ],
  "street": String,
  "neighbourhood": String,
  "neighbourhood_cleansed": String,
  "neighbourhood_group_cleansed": String,
  "city": String,
  "state": String,
  "zipcode": Number,
  "market": String,
  "smart_location": String,
  "country_code": String,
  "country": String,
  "latitude": Number,
  "longitude": Number,
  "property_type": String,
  "room_type": String,
  "accommodates": Number,
  "bathrooms": Number,
  "bedrooms": Number,
  "beds": Number,
  "bed_type": String,
  "amenities":[
     String,
     String,
     String,
     String,
     String,
     String,
     String,
     String,
     String,
     String,
     String,
     String,
     String,
     String,
     String
  ],
  "square_feet":Boolean,
  "price":Number,
  "weekly_price":Boolean,
  "monthly_price":Boolean,
  "security_deposit":Boolean,
  "cleaning_fee":Boolean,
  "guests_included":Number,
  "extra_people":Number,
  "minimum_nights":Number,
  "maximum_nights":Number,
  "calendar_updated": String,
  "has_availability":Boolean,
  "availability_30":Number,
  "availability_60":Number,
  "availability_90":Number,
  "availability_365":Number,
  "calendar_last_scraped": String,
  "number_of_reviews": Number,
  "first_review": String,
  "last_review": String,
  "review_scores_rating": Number,
  "review_scores_accuracy": Number,
  "review_scores_cleanliness":Number,
  "review_scores_checkin":Number,
  "review_scores_communication":Number,
  "review_scores_location":Number,
  "review_scores_value":Number,
  "license":Boolean,
  "jurisdiction_names":Boolean,
  "cancellation_policy":String,
  "calculated_host_listings_count":Number,
  "reviews_per_month":Number,
  "geolocation":{
     "lon": Number,
     "lat":Number
  },
  "features":[
     String,
     String,
     String
  ]
});

export default mongoose.model('Airbnb', airbnbSchema);
